import { Recursive } from 'next/font/google'
import "./globals.css";

const recursive = Recursive({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={recursive.className}>{children}</body> {/* Use the correct variable */}
    </html>
  );
}
